# Generated by Django 5.0.6 on 2024-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_drinking_habits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
